# Generated by Django 4.1 on 2024-04-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTDweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originimg',
            name='name',
            field=models.CharField(max_length=128, verbose_name='图片名'),
        ),
    ]
