# Generated by Django 5.0.4 on 2024-04-15 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTDweb', '0005_predictedimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='模型名')),
                ('video_weight', models.CharField(max_length=128, verbose_name='文件地址')),
            ],
        ),
        migrations.CreateModel(
            name='OriginVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='视频名')),
                ('img_path', models.CharField(max_length=256, verbose_name='图片地址')),
                ('is_detect', models.SmallIntegerField(choices=[(0, '未监测'), (1, '已监测')], default=0, verbose_name='是否监测')),
                ('folder_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTDweb.detectset', verbose_name='集合名')),
            ],
        ),
        migrations.AddField(
            model_name='detectset',
            name='to_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RTDweb.videomodel', verbose_name='视频模型'),
        ),
    ]
