# Generated by Django 5.0.4 on 2024-04-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTDweb', '0006_videomodel_originvideo_detectset_to_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='originvideo',
            name='cover_img_path',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='封面地址'),
        ),
    ]
