# Generated by Django 5.0.4 on 2024-04-17 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTDweb', '0007_originvideo_cover_img_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='视频名')),
                ('img_path', models.CharField(max_length=256, verbose_name='视频地址')),
                ('cover_img_path', models.CharField(blank=True, max_length=256, null=True, verbose_name='封面地址')),
                ('folder_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTDweb.detectset', verbose_name='集合名')),
                ('oring_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTDweb.originvideo', verbose_name='原视频')),
            ],
        ),
    ]
