# Generated by Django 5.0.4 on 2024-04-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTDweb', '0008_predictedvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectset',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'img'), (2, 'video'), (3, 'camera')], verbose_name='类别'),
        ),
    ]
