# Generated by Django 5.0.4 on 2024-04-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTDweb', '0009_alter_detectset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectset',
            name='camera_id',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='摄像头编号'),
        ),
    ]
